export const defaultSettings = {
	background: '#FFFFFF00',
	color: '#ffffff',
	images: [],
	headingFontSize: 44,
	summaryFontSize: 25,
	width: 2312/4,
	height: 1468/4,
	radius: 0,
	border: 0,
	borderColor: '#333',
	// bgUrl: 'https://source.unsplash.com/random/1280x807?programming',
	exportExt: 'png',
	font: 'Droid Sans',
	overlay: 0,
	file_name: 'The_Jinx_Banner',
	primary:'#53DFF6',
	secondary:'#FFB4DB',
	number:0,
	name:"",
};
